import random

print(random.randint(5, 20))  # line 1
print(random.randrange(3, 10, 2))  # line 2
print(random.uniform(2.5, 5.5))  # line 3

# What did you see on line 1?
# Smallest Number Possible: 5
# Largest Number Possible: 20

# What did you see on line 2?
# Smallest Number Possible: 3
# Largest Number Possible: 9
# Can it Produce a 4?: No, because 4 is not in the sequence generated by range(3, 10, 2).

# What did you see on line 3?
# Smallest Number Possible: 2.5
# Largest Number Possible: Just below 5.5

import random

random_number = random.randint(1, 100)
print(random_number)
